<?php
require_once __DIR__.'/includes/functions.php';require_login();$me=user();$pdo=db();$page_title='Command Center';
[$lo,$hi]=xp_bounds((int)$me['xp']);$pct=$hi>$lo?min(100,max(0,((int)$me['xp']-$lo)/($hi-$lo)*100)):0;
$active=$pdo->prepare("SELECT q.*,qp.status,c.name category FROM quest_participants qp JOIN quests q ON q.id=qp.quest_id JOIN categories c ON c.id=q.category_id WHERE qp.user_id=? AND qp.status IN ('requested','accepted','in_progress') ORDER BY q.scheduled_at ASC LIMIT 4");$active->execute([$me['id']]);$active=$active->fetchAll();
$recent=$pdo->prepare("SELECT q.*,qp.status,c.name category FROM quest_participants qp JOIN quests q ON q.id=qp.quest_id JOIN categories c ON c.id=q.category_id WHERE qp.user_id=? AND qp.status='completed' ORDER BY qp.completed_at DESC LIMIT 4");$recent->execute([$me['id']]);$recent=$recent->fetchAll();
$near=$pdo->query("SELECT q.*,c.name category,u.username FROM quests q JOIN categories c ON c.id=q.category_id JOIN users u ON u.id=q.creator_id WHERE q.status='open' ORDER BY q.created_at DESC LIMIT 3")->fetchAll();
$ach=$pdo->prepare("SELECT a.* FROM user_achievements ua JOIN achievements a ON a.id=ua.achievement_id WHERE ua.user_id=? ORDER BY ua.earned_at DESC LIMIT 6");$ach->execute([$me['id']]);$ach=$ach->fetchAll();
$completed=(int)$pdo->query("SELECT COUNT(*) FROM quest_participants WHERE user_id=".(int)$me['id']." AND status='completed'")->fetchColumn();
$created=(int)$pdo->query("SELECT COUNT(*) FROM quests WHERE creator_id=".(int)$me['id'])->fetchColumn();
$rank=(int)$pdo->query("SELECT 1+COUNT(*) FROM (SELECT u.id,COUNT(qp.id) c FROM users u LEFT JOIN quest_participants qp ON qp.user_id=u.id AND qp.status='completed' GROUP BY u.id) x WHERE x.c > ".$completed)->fetchColumn();
require __DIR__.'/includes/header.php';
?>
<div class="dashboard"><div class="dash-welcome"><div><span class="eyebrow">PLAYER COMMAND CENTER</span><h1>WELCOME BACK, <em><?=e(strtoupper($me['username']))?></em>.</h1><p>Your next mission is out there.</p></div><a class="btn gold" href="<?=base_url('create-quest.php')?>">+ Post a Quest</a></div>
<div class="player-banner"><div class="player-id"><?=avatar_markup($me, 'big-avatar')?><div><span>PLAYER</span><h2><?=e($me['username'])?></h2><small>LEVEL <?=e($me['level'])?> · RANK #<?=e($rank)?></small></div></div><div class="xp-block"><div><span>XP PROGRESS</span><strong><?=number_format((int)$me['xp'])?> <small>/ <?=number_format($hi)?></small></strong></div><div class="progress"><i style="width:<?=$pct?>%"></i></div></div><div class="capacity"><span>ACTIVE QUEST CAPACITY</span><strong><?=active_quest_count($me['id'])?> / <?=quest_capacity((int)$me['level'])?></strong></div></div>
<div class="dash-grid"><section><div class="section-head"><div><span class="eyebrow">CURRENT MISSIONS</span><h2>ACTIVE QUESTS</h2></div><a href="<?=base_url('quests.php')?>" class="text-link">Quest Board →</a></div><?php foreach($active as $q):?><a class="dash-quest" href="<?=base_url('quest.php?id='.$q['id'])?>"><div><small><?=e($q['category'])?></small><h3><?=e($q['title'])?></h3><span><?=e(status_label($q['status']))?> · <?=date('M j',strtotime($q['scheduled_at']))?></span></div><b>+<?=$q['xp_reward']?> XP</b></a><?php endforeach;if(!$active):?><div class="empty">No active quests. The board is waiting.</div><?php endif;?></section>
<section><div class="section-head"><div><span class="eyebrow">RECENT WINS</span><h2>COMPLETED</h2></div></div><?php foreach($recent as $q):?><div class="dash-quest"><div><small><?=e($q['category'])?></small><h3><?=e($q['title'])?></h3><span>CONFIRMED</span></div><b>+<?=$q['xp_reward']?> XP</b></div><?php endforeach;if(!$recent):?><div class="empty">Complete a quest to start your record.</div><?php endif;?></section></div>
<div class="dash-grid lower"><section><div class="section-head"><div><span class="eyebrow">NEARBY INTEL</span><h2>QUESTS TO CONSIDER</h2></div></div><?php foreach($near as $q):?><a class="compact-card" href="<?=base_url('quest.php?id='.$q['id'])?>"><div><span class="eyebrow"><?=e($q['category'])?></span><h3><?=e($q['title'])?></h3><p>⌖ <?=e($q['location'])?></p></div><strong>+<?=$q['xp_reward']?> XP</strong></a><?php endforeach;?></section>
<section><div class="section-head"><div><span class="eyebrow">BADGES</span><h2>ACHIEVEMENTS</h2></div><a href="<?=base_url('achievements.php')?>" class="text-link">View all →</a></div><div class="badges"><?php foreach($ach as $a):?><div class="badge-card"><div class="badge-icon">✦</div><b><?=e($a['name'])?></b><small><?=e($a['description'])?></small></div><?php endforeach;if(!$ach):?><div class="empty">Your first badge is one completed quest away.</div><?php endif;?></div></section></div></div>
<?php require __DIR__.'/includes/footer.php'; ?>
