<?php
require_once __DIR__.'/../includes/functions.php';require_admin();$pdo=db();$page_title='Admin Control';
$counts=[];foreach(['users','quests','reports','reward_transactions'] as $t)$counts[$t]=(int)$pdo->query("SELECT COUNT(*) FROM $t")->fetchColumn();
$reports=$pdo->query("SELECT r.*,u.username,q.title FROM reports r JOIN users u ON u.id=r.reporter_id JOIN quests q ON q.id=r.quest_id ORDER BY r.created_at DESC LIMIT 10")->fetchAll();
require __DIR__.'/../includes/header.php';
?>
<div class="admin"><div class="page-head compact"><div><span class="eyebrow">ADMINISTRATION</span><h1>CONTROL ROOM.</h1><p>Moderate the community and configure the game economy.</p></div></div>
<div class="admin-actions"><a class="btn gold" href="<?=base_url('admin/users.php')?>">Manage Users</a><a class="btn gold" href="<?=base_url('admin/quests.php')?>">Manage Quests</a></div><div class="admin-stats"><?php foreach($counts as $k=>$v):?><div><span><?=e(strtoupper(str_replace('_',' ',$k)))?></span><b><?=$v?></b></div><?php endforeach;?></div>
<div class="admin-grid"><section><div class="section-head"><div><span class="eyebrow">MODERATION</span><h2>RECENT REPORTS</h2></div></div><?php foreach($reports as $r):?><div class="report"><span class="status"><?=$r['status']?></span><div><b><?=e($r['reason'])?></b><p><?=e($r['title'])?> · reported by <?=e($r['username'])?></p><small><?=e($r['details'])?></small></div><form method="post" action="<?=base_url('admin/report.php')?>"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=$r['id']?>"><?php if($r['status']==='open'): ?><button class="small-btn" name="action" value="resolve">Resolve</button><button class="small-btn danger-text" name="action" value="dismiss">Dismiss</button><?php endif; ?></form></div><?php endforeach;if(!$reports):?><div class="empty">No reports.</div><?php endif;?></section>
<section><div class="section-head"><div><span class="eyebrow">SYSTEM SETTINGS</span><h2>ECONOMY</h2></div></div><form method="post" action="<?=base_url('admin/settings.php')?>" class="form-grid"><?php foreach(['PLATFORM_FEE_PERCENT','LEADERBOARD_POOL_SHARE','DEVELOPMENT_SHARE','CHAMPION_PRIZE_PERCENT'] as $key):$s=$pdo->prepare("SELECT setting_value FROM admin_settings WHERE setting_key=?");$s->execute([$key]);$val=$s->fetchColumn();?><label><?=e($key)?><input name="<?=e($key)?>" value="<?=e($val)?>"></label><?php endforeach;?><button class="btn gold">Save Settings</button></form></section></div></div>
<?php require __DIR__.'/../includes/footer.php'; ?>
